import type { Metadata } from "next";
import "./globals.css";
import { Header, Footer } from "@/components/server/indexServer";
import { StateProvider } from "@/context/CurrentStateContext";
import { AuthProvider } from "@/context/AuthContext";
import PostHogProvider from "@/PostHogProvider";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Marenne Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 p-0 w-full min-h-screen box-border overflow-x-hidden antialiased">
        <PostHogProvider>
          <AuthProvider>
            <StateProvider>
              <Header />
              {children}
              <Footer />
            </StateProvider>
          </AuthProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
