import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/server/Header";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Marenne Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 p-0 w-full min-h-screen box-border overflow-x-hidden antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
